name: Build

on:
  push:
    branches:
      - main
      - staging
      - production
  pull_request:
    # Build all PRs
  # HACK: also listen on workflow_run to avoid needing to set up PAT
  workflow_run:
    workflows:
      - Prepare Release Branch
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.test.outputs.test }}
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Generate output
        id: test
        run: echo "::set-output name=test::hello"
