name: Do stuff on comment

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  pr:
    name: PR comment
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: respond with text
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Looks like you want to *deploy*

      - name: respond with reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "+1"

      - name: trigger deploy-reusable
        uses: ./.github/workflows/deploy-reusable.yml
        with:
          environment-name: production
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: respond with reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
