name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: Target environment
        options:
          - staging
          - production
        required: true
        type: choice

jobs:
  staging:
    name: Staging
    if: inputs.target == 'staging'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment-name: staging
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prod:
    name: Production
    if: inputs.target == 'production'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment-name: production
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # just to simulate other one!
  through-other-event:
    name: Proxy to receive event
    runs-on: ubuntu-latest
    steps:
      - name: Call other one through curl
        # ID comes from https://api.github.com/repos/Firehed/actions-experiments/actions/workflows
        run: >
          curl
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          -d '{"ref":"${{ github.ref }}","inputs":{"overlay":"${{ inputs.target }}","image":"alpine:${{ github.sha }}"}}'
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/38274832/dispatches
