name: Receive Event

on:
  repository_dispatch:
    # all events?

jobs:
  deploy-with-kustomize:
    # if: github.event.action = 'deploy'
    uses: ./.github/workflows/deploy-kustomize.yml
    with:
      image: ${{ github.event.client_payload.image }}
      overlay: ${{ github.event.client_payload.overlay }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

