name: Workflow Run

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
      - staging
      - production
    types:
      - completed

jobs:
  show-context:
    name: Show context
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  run-on-main:
    name: Runs on main
    if: github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo Ran on main

  run-on-staging:
    name: Runs on staging
    if: github.event.workflow_run.head_branch == 'staging'
    runs-on: ubuntu-latest
    steps:
      - run: echo Ran on production

  run-on-production:
    name: Runs on main
    if: github.event.workflow_run.head_branch == 'production'
    runs-on: ubuntu-latest
    steps:
      - run: echo Ran on production
